/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package x20170920;

/**
 *
 * @author Tanulo
 */
public class SzemelyiSzamFrame extends javax.swing.JFrame {

    /**
     * Creates new form SzemelyiSzamFrame
     */
    public SzemelyiSzamFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSzemelyiSzam = new javax.swing.JLabel();
        tfSzemelyiSzam = new javax.swing.JTextField();
        btEllenorzes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbErvenyesseg = new javax.swing.JLabel();
        lbNem = new javax.swing.JLabel();
        lbSzuletesiDatum = new javax.swing.JLabel();
        lbAllampolgarsag = new javax.swing.JLabel();
        lbErvenyessegErtek = new javax.swing.JLabel();
        lbNemErtek = new javax.swing.JLabel();
        lbSzuletesiDatumErtek = new javax.swing.JLabel();
        lbAllampolgarsagErtek = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbSzemelyiSzam.setText("Személyi szám:");

        btEllenorzes.setText("Ellenőrzés");
        btEllenorzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEllenorzesActionPerformed(evt);
            }
        });

        lbErvenyesseg.setText("Érvényesség:");

        lbNem.setText("Nem:");

        lbSzuletesiDatum.setText("Születési dátum:");

        lbAllampolgarsag.setText("Állampolgárság:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbErvenyesseg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbErvenyessegErtek))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbNem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNemErtek))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbSzuletesiDatum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSzuletesiDatumErtek))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbAllampolgarsag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAllampolgarsagErtek)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbAllampolgarsag, lbErvenyesseg, lbNem, lbSzuletesiDatum});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbErvenyesseg)
                    .addComponent(lbErvenyessegErtek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNem)
                    .addComponent(lbNemErtek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSzuletesiDatum)
                    .addComponent(lbSzuletesiDatumErtek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAllampolgarsag)
                    .addComponent(lbAllampolgarsagErtek))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbSzemelyiSzam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSzemelyiSzam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEllenorzes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSzemelyiSzam)
                    .addComponent(tfSzemelyiSzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEllenorzes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEllenorzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEllenorzesActionPerformed
        lbErvenyessegErtek.setText("");
        lbNemErtek.setText("");
        lbSzuletesiDatumErtek.setText("");
        lbAllampolgarsagErtek.setText("");
        
        String szemelyiSzam = tfSzemelyiSzam.getText();
        
        boolean ervenyes = ervenyes(szemelyiSzam);
        lbErvenyessegErtek.setText(ervenyes ? "Érvényes" : "Érvénytelen");
        
        if (ervenyes) {
            informacioKiiras(szemelyiSzam);
        }
    }//GEN-LAST:event_btEllenorzesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SzemelyiSzamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SzemelyiSzamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SzemelyiSzamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SzemelyiSzamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SzemelyiSzamFrame().setVisible(true);
            }
        });
    }
    
    private boolean ervenyes(String szemelyiSzam) {
        final int HOSSZ = 11;
        if (szemelyiSzam.length() != HOSSZ) {
            return false;
        }
        
        int ee = Integer.parseInt(szemelyiSzam.substring(1, 3));
        
        int sum = 0;
        if (ee < 97) {
            for (int i = 0; i < HOSSZ; i++) {
                sum += (i + 1) * szemelyiSzam.charAt(i);
            }
        } else {
            for (int i = HOSSZ - 1; i > 0; i--) {
                sum += i * szemelyiSzam.charAt(i - 1);
            }
        }
        int k = sum % 11;
        
        if (k == 10) { //10 nem kiosztható
            return false;
        }
        
        if (k == Integer.parseInt(szemelyiSzam.substring(HOSSZ - 1))) { // számított ellenőrző számjegy egyezik a megadottal
            return true;
        }
        
        return false;
    }
    
    private void informacioKiiras(String szemelyiSzam) {
        int m = Integer.parseInt(szemelyiSzam.substring(0, 1));
        String ee = szemelyiSzam.substring(1, 3);
        int hh = Integer.parseInt(szemelyiSzam.substring(3, 5));
        int nn = Integer.parseInt(szemelyiSzam.substring(5, 7));
        
        lbNemErtek.setText(m % 2 == 0 ? "Nő" : "Férfi");
        
        String szuletesiEv = new String();
        if (m == 1 || m == 2 || m == 5 || m == 6) {
            szuletesiEv += "19";
        } else if (m == 3 || m == 4 || m == 7 || m == 8) {
            szuletesiEv += "18";
        }
        szuletesiEv += ee;
        lbSzuletesiDatumErtek.setText(szuletesiEv + "." + padTen(hh) + "." + padTen(nn) + ".");
        
        String allampolgarsag = "";
        if (m <= 1 && m <= 4) {
            if (Integer.parseInt(szuletesiEv) < 1997) {
                allampolgarsag = "magyar";
            } else {
                allampolgarsag = "nem tudni";
            }
        } else if (m <= 5 && m <= 8) {
            allampolgarsag = "eredetileg nem magyar";
        }
        lbAllampolgarsagErtek.setText(allampolgarsag);
    }
    
    private String padTen(int a) {
        if (a < 10) {
            return '0' + Integer.toString(a);
        }
        return Integer.toString(a);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEllenorzes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAllampolgarsag;
    private javax.swing.JLabel lbAllampolgarsagErtek;
    private javax.swing.JLabel lbErvenyesseg;
    private javax.swing.JLabel lbErvenyessegErtek;
    private javax.swing.JLabel lbNem;
    private javax.swing.JLabel lbNemErtek;
    private javax.swing.JLabel lbSzemelyiSzam;
    private javax.swing.JLabel lbSzuletesiDatum;
    private javax.swing.JLabel lbSzuletesiDatumErtek;
    private javax.swing.JTextField tfSzemelyiSzam;
    // End of variables declaration//GEN-END:variables
}
